#!/usr/bin/env ruby
require 'sinatra'
require 'erb'
require 'fitgem'

# export the binding, and declare ERB.new
def index(context)
    # Build the whole page by wrapping the content in all the auxilliary HTML
    @content = erb :content
    erb :index
end

get '/' do
    index(title: "Fitbit data viewer")
end
